baseURL = ""
languageCode = 'en-us'
title = 'SG'
theme = 'LoveIt-master'






[[menu.main]]
    name = "Life"
    url = "/Life/"
    weight = 3

[[menu.main]]
    name = "."
    url = "/Overthinking/"
    weight = 9

[[menu.main]]
    name = "love"
    url = "/love/"
    weight = 7

[[menu.main]]
    name = "About"
    url = "/author/"
    weight = 1      
   
[[menu.main]]
    name = "Quotes"
    url = "/quotes/"
    weight = 5  

   