baseURL = ""
languageCode = 'en-us'
title = 'SG'
theme = 'LoveIt-master'






[[menu.main]]
    name = "Life"
    url = "/Life/"
    weight = 3

[[menu.main]]
    name = "."
    url = "/Overthinking/"
    weight = 7

[[menu.main]]
    name = "love"
    url = "/love/"
    weight = 5

[[menu.main]]
    name = "About me"
    url = "/author/"
    weight = 1      

   