baseURL = ""
languageCode = 'en-us'
title = 'SG'
theme = 'LoveIt-master'






[[menu.main]]
    name = "."
    url = "/Life/"
    weight = 1

[[menu.main]]
    name = "Overthinking"
    url = "/Overthinking/"
    weight = 4

   